### ISSUE TITLE
__deleted__

### ISSUE THREAD

**Issue by PatrickGretzki** [2dom/P10_matrix#2]
Hey,

first thanks for the great source code and the wonderul idea of pin reduction !

I just finished wiring up my display, but I only can see jumbled-up pixels.

The test script "P10_pattern_test.ino" creates the following sequence:
- 1st line red / 9th line red
- 1st line yellow / 9th line yellow
- 1st line white / 9th line white
- 2nd line red / 10th line red
- and so on...

The second part of the test script (where the text "Pixel" is displayed in cyan) only created non-sense (see picture)
![img_20180121_131950](https://user-images.githubusercontent.com/3587300/35194616-60d1fe94-feb6-11e7-81ce-ff763511f4ed.jpg)

**Comment by 2dom** [comment]
Hi there,

please re-check the connections for A,B,C. If this does not work you might want to try a previous version of the driver:

https://github.com/2dom/P10_matrix/tree/788d6760dfeee1bde4ea53fd4c1257c313a92615 <https://github.com/2dom/P10_matrix/tree/788d6760dfeee1bde4ea53fd4c1257c313a92615>

I recently added some new features to the library and was not able to test it on the 8 row-step display.

Let me know if this fixes it.

Cheers

Dom

**Comment by 2dom** [comment]
Hey,

you might have forgotten to change #define pattern4 to pattern8 in the header file.

Best

Dom

**Comment by PatrickGretzki** [comment]
Thank you for your advise. 
There was a loose contact in one of the address lines (A,B,C), so that some pixels were overwritten, resulting in the strange behaviour.
Now it's working perfectly!

**Comment by 2dom** [comment]
Yay - Glad it works ! 

Best Regards 

Dom
