### ISSUE TITLE
scrambled display

### ISSUE THREAD

**Issue by pakeonoahu** [2dom/P10_matrix#3]
Hi, 
    I tested my P10 1/8 scan using Arduino nano and it worked fine, after loading your code on ESP-12, and setup all the jumpers, the P10_pattern_test works, but pixeltime was scrambled, I tried to print just text starting at 2,0 (display.setCursor(2,0), the text are also scrambled, looks like it started from 2,8 and wrap back up to the top with some weird spacing.  I have tried it on different ESP-12 and same problem, any idea what might cause that?

thanks,
p.

**Comment by pakeonoahu** [comment]
Okay, found my problem, after drawing few pixels and the location are off by 9(x and y), I found P10_matrix.h  has "#define PATTERN4" enabled, no matter what I put in the test example code it default back to 1/4 scan, changing that to 1/8 solve my issue.  Thanks for writing the ESP8266 driver for the P10 panel, it works!

**Comment by 2dom** [comment]
Great! Thanks for the feed-back.

Cheers

Dom
