### ISSUE TITLE
How to connect the power supply?

### ISSUE THREAD

**Issue by brotsignatur** [2dom/P10_matrix#4]
Hi Dominic,

thanks for the wonderful inspiration. I would like to build my own device, but i am struggling with the connection of the power supply. Did you simply connect VCC and GND of the LED panel to the 5V and GND pins of the nodemcu? Does that give enough amps for driving the leds (i am assuming that those displays need around 2A)?

Thanks for your answer,

Sven

**Comment by 2dom** [comment]
Dear Sven,

Check the Schematics out for the NodeMcu (google). There is a diode between the 5v from the USB port and the onboard step-down.

I simply soldered the the VCC for the panel to the Anode of this diode.

I hope hat helps

Dom
