### ISSUE TITLE
P5 32x64 pattern support

### ISSUE THREAD

**Issue by irazaq** [2dom/P10_matrix#7]
Thanks for sharing this project. I am trying to extend this to support P5 panel which is 32x64 1/16scan . I was able to get the displayTestPattern to work showing 2 lines of 16 rows separation, but I am having problem with normal text display. How do I determine the correct pattern for the panel?

**Comment by 2dom** [comment]
Could you send me video of the test pattern? I will try to support that display.

**Comment by irazaq** [comment]
[P5_files.zip](https://github.com/2dom/P10_matrix/files/1835770/P5_files.zip)
In the attached are the video, and the souce codes of my modifications. Thanks for your help.

**Comment by 2dom** [comment]
I think you added all the right bits and pieces ... the problem appears to be that the D signal is not coming through. You used GPIO3 for D which conflicts with your Serial interfaces. So may want to chose another pin for D and double check the connection.

**Comment by irazaq** [comment]
The D signal is OK, I change it to D6 still same result. The video I uploaded was cut-off because of the size. I manage to reduce the video size to 25percent which show the full scan. The image I attached before shows the "pixel time" display and you can see that the colour offsets are wrong while the text display correctly. That's why I thought there is something I am missing with the respect to the colour mapping and pixel pattern. Attached is the full video scaled down.
[P5_pattern-25size.mp4.zip](https://github.com/2dom/P10_matrix/files/1839693/P5_pattern-25size.mp4.zip)
I will continue to play with it and let you know my progress.

**Comment by irazaq** [comment]
I was able to figure out the issues, total_offset_r, total_offset_g, total_offset_b type was the issue. Changed them to uint16_t and problem solved. I have sent a pull request of the changes I have made.

**Comment by irazaq** [comment]
forgot to add the video
[P5_working.mp4.zip](https://github.com/2dom/P10_matrix/files/1845980/P5_working.mp4.zip)

**Comment by 2dom** [comment]
Dear irazaq ... I hat some time this weekend and extended the library to support all available panels.
Check out https://github.com/2dom/PxMatrix. I also improved the performance quite a bit. 

Do you mind testing it if works with your panel?

You now have to set the resolution in the constructor:

`PxMATRIX display(64,32, P_LAT, P_OE,P_A,P_B,P_C,P_D);`

and set the pattern in the `display.begin(16)` call

Thanks

Dom

**Comment by irazaq** [comment]
Cool, will test it out. That surely makes it easy to configure the lib.

**Comment by NetForces** [comment]
@2dom do you think that would work with 2 32x16 panels linked together ? Either treat it as a 64x16 or a 32x32 ?

**Comment by 2dom** [comment]
@NetForces  Ha!...didn’t think about that one ... I don’t see why not :)

**Comment by NetForces** [comment]
I can give it a try, but what would be the connection ?

Just cascade the 2 panels (out1 -> in2) and the same loopback signals going from out2 to in1 ?

I already have 1 panel (32x16) working with P10_matrix right now using a Wemos D1 board

**Comment by 2dom** [comment]
Yes ... that would be the set-up I suppose. Let me know if it works ... this is exciting!

**Comment by 2dom** [comment]
Yes ... that would be the set-up I suppose. Let me know if it works ... this is exciting!

**Comment by NetForces** [comment]
Should be able to test that by the week-end.

**Comment by irazaq** [comment]
tested the new code and it works on P5. 
Pixel draw latency in us: 3
Display update latency in us: 467
Note that at show_time between 40 and  70, the system crash with "Soft WDT reset" after showing "Pixel Time" ie when in the loop.
But it works fine for show_time less than or equal to 30.
![0328180014a](https://user-images.githubusercontent.com/431541/38063239-07459d4c-32c6-11e8-81bc-b52c746fd11b.jpg)
For the question of 2 16x32 it should work as 16x64, to work as 32x32, it will need the D select line if I am not wrong. We may need to implement a virtual board to support chaining in any combination like the raspberry pi project here https://github.com/hzeller/rpi-rgb-led-matrix

**Comment by 2dom** [comment]
Great ... thanks for the feed-back. Can you try feeding the watchdog before you call display?

void display_updater()
{
  ESP.wdtFeed();
  display.display(70);

}

**Comment by 2dom** [comment]
Please continue discussion at https://github.com/2dom/PxMatrix/issues/1 since it refers to the new library ...
